# Generated by Django 5.0.6 on 2024-08-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_url',
            field=models.URLField(blank=True),
        ),
    ]
