# Generated by Django 5.0.4 on 2024-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='author',
            field=models.ManyToManyField(related_name='movies', to='movie.author'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movie.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='kp_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
