# Generated by Django 5.0.4 on 2024-04-22 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_author_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 4, 22, 9, 15, 57, 827915, tzinfo=datetime.timezone.utc), max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
