# Generated by Django 5.0.6 on 2024-08-07 10:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='movie',
        ),
        migrations.AddField(
            model_name='role',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='movie.movie'),
            preserve_default=False,
        ),
    ]
