# Generated by Django 5.0.4 on 2024-04-22 09:30

import datetime
import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=django_countries.fields.CountryField(default=datetime.datetime(2024, 4, 22, 9, 30, 57, 292624, tzinfo=datetime.timezone.utc), max_length=746, multiple=True),
            preserve_default=False,
        ),
    ]
