# Generated by Django 5.0.6 on 2024-08-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_role_movie_role_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
