# Generated by Django 5.0.4 on 2024-04-22 09:31

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
    ]
