# Generated by Django 5.0.6 on 2024-08-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
