# Generated by Django 5.0.6 on 2024-08-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='related_films',
            field=models.ManyToManyField(blank=True, to='movie.movie'),
        ),
    ]
