# Generated by Django 5.0.4 on 2024-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('red', 'Danger'), ('orange', 'Warning'), ('lightbule', 'Info'), ('green', 'Success')], max_length=250)),
                ('doned', models.BooleanField(default=False)),
            ],
        ),
    ]
