# Generated by Django 5.0.4 on 2024-06-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Kurs nomi')),
                ('duration', models.CharField(max_length=250, verbose_name='Davomiyligi')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Guruh nomi')),
                ('teach_days', models.CharField(choices=[('dchj', 'Du-Chor-Ju'), ('spsh', 'Se-Pa-Sha')], max_length=250)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('room', models.PositiveSmallIntegerField(default=0)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=250, verbose_name='Familya')),
                ('phone', models.CharField(max_length=250, verbose_name='Telefon')),
                ('address', models.CharField(max_length=250, verbose_name='Manzil')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='main.group')),
            ],
        ),
    ]
