# Generated by Django 4.2.7 on 2024-03-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ishchi ismi: ')),
                ('surname', models.CharField(max_length=150, verbose_name='Ishchi familiyasi: ')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Ishchi raqami: ')),
                ('email', models.EmailField(max_length=254, verbose_name='Ishchi email: ')),
                ('image', models.ImageField(upload_to='worker_image', verbose_name='Ishchi rasmi: ')),
                ('about', models.TextField(verbose_name='Ishchi haqida: ')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Leaguage',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
