# Generated by Django 4.2.7 on 2024-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_worker_remove_player_club_delete_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ishchi statusi: '),
        ),
    ]
