# Generated by Django 4.2.7 on 2024-04-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_worker_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Klub nomi')),
                ('logo', models.ImageField(upload_to='club/logos/')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('coach', models.CharField(max_length=100, verbose_name='Trener')),
            ],
        ),
        migrations.CreateModel(
            name='Leaguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Liga yoki Chempionat nomi')),
                ('logo', models.ImageField(upload_to='leaguage/logos/')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ism-Sharif')),
                ('image', models.ImageField(upload_to='players/images/')),
                ('date_of_birth', models.DateField(verbose_name='Tugilgan sanasi')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('position', models.CharField(choices=[('gk', 'Darvozabon'), ('df', 'Himoyachi'), ('md', 'Yarim himoyachi'), ('fw', 'Hujumkor himoyachi'), ('st', 'Hujumchi')], max_length=100)),
                ('transfer_summa', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.club')),
            ],
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AddField(
            model_name='club',
            name='leaguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.leaguage'),
        ),
    ]
