# Generated by Django 5.0.4 on 2024-06-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Liga nomi')),
                ('logo', models.ImageField(blank=True, upload_to='leaguages/')),
                ('country', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Klub nomi')),
                ('logo', models.ImageField(blank=True, upload_to='clubs/')),
                ('country', models.CharField(max_length=250)),
                ('leaguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='players.leaguage')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Player nomi')),
                ('image', models.ImageField(blank=True, upload_to='players/')),
                ('country', models.CharField(max_length=250)),
                ('date_of_birth', models.DateTimeField()),
                ('height', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('position', models.CharField(choices=[('gk', 'Darvozabon'), ('df', 'Himoyachi'), ('mdf', 'Yarim Himoyachi'), ('fw', 'Hujumkor himoyachi'), ('st', 'Hujumchi')], max_length=50)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.club')),
            ],
        ),
    ]
